global:
  name: consul
  image: consul:1.8.0
  imageK8S: hashicorp/consul-k8s:0.16.0
  datacenter: dc1

ui:
  service:
    type: LoadBalancer

syncCatalog:
  enabled: true
  toConsul: true
  toK8S: true